
name: Node JS web CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Run node.js tests
        run: |
         npm install jest
         npx jest
        

#CD
#Build and push Docker image
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
          terraform_wrapper: false # Crucial for raw output capture

    - name: Terraform Init
      run: terraform init
      working-directory: ./infrastructure/Terraform

    - name: Get EC2 IP
      working-directory: ./infrastructure/Terraform
      id: get_ip
      run: |
        # 1. Get the list of IPs from Terraform in JSON format
        # 2. Use jq to join them with a comma: "IP1,IP2"
        # 3. Save the result to $GITHUB_OUTPUT
        IPS=$(terraform output -json ec2_public_ip_address | jq -r 'join(",")')
        echo "ec2_ips=$IPS" >> $GITHUB_OUTPUT
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PATOKEN }}

        
    - name: Deploy to Docker Hub
      uses: docker/build-push-action@v4
      with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: karimrushdy/konvert_to_convert:latest


# Pull and run the Docker container on AWS EC2 instance
    - name: SSH and deploy container
      uses: appleboy/ssh-action@v0.1.7
      with:
         # host: ${{ steps.get_ip.output.ec2_ips }}
          host: ${{ secrets.EC2_IPS }}
          username: ubuntu
          key: ${{ secrets.EC2SSH }}
          script: |
            docker pull karimrushdy/konvert_to_convert:latest
            docker stop konvert_container || true
            docker rm konvert_container || true
            docker run -d --name konvert_container -p 80:3000 karimrushdy/konvert_to_convert:latest

    - name: Image Info
      run: docker images
